### ISSUE TITLE
conditional node "if" argument needed in args list

### ISSUE THREAD

**Issue by felixplajer** [square/spincycle#109]
When writing a request/sequence with a conditional node, sometimes the grapher will fail if the "if" arg isn't included in the args list. i.e. 
```
this-is-a-node:
  type: conditional
  if: thisIsAnArg
  args:
    - expected: anotherArg
       given: anotherArg
    # thisisAnArg should NOT be required here
  sets: []
  deps: []
```
The error I get when trying to run a request is like this: `API error: in seq sequence_***, node ***: 'if' arg '***' not set (HTTP status 500)`.
Sometimes it _does_ work without that arg in the args list though - it doesn't change per node, it always fails for some conditional nodes, and it always succeeds for others.
