### ISSUE TITLE
Limiting the number of parallel sequences that run at once

### ISSUE THREAD

**Issue by michaelfinch** [square/spincycle#115]
It would be nice if parallel sequences could be limited to only run N at a time. It would look something like this in the yaml spec
```
job1:
  category: sequence
  type: the/sequence
  each:
    - foo:bar
  parallel: 1
```
Even if job1 expanded into 5 parallel sequences, only 1 would run at a time.
