### ISSUE TITLE
Grapher doesn't account for dependencies when creating jobs

### ISSUE THREAD

**Issue by felixplajer** [square/spincycle#117]
Right now, the grapher decides what order to Create jobs in based only on what args each job requires (i.e. a job can be created as long as all the args it needs are present). Dependencies are only used when putting the jobs in final order in the graph (aka deciding the order to Run them).

This causes some issues if you want to run a job that sets an arg twice at different points of the same request. For example, in this case I intend `do-something-job-1` to use the `someArg` set by `sets-arg-1` and `do-something-job-2` to use the `someArg` set by `sets-arg-2`, but really it's random which job gets what version of `someArg`:
```
sets-arg-1:
  category: job
  type: set-arg-job
  sets: [someArg]
  deps: []
do-something-job-1:
  category: job
  type: use-arg-job
  arg:
    - expected: arsomeArg1
      given: someArg
  sets: []
  deps: [sets-arg-1]
# ... other stuff in the request
sets-arg-2:
  category: job
  type: set-arg-job
  sets: [someArg]
  deps: []
do-something-job-2:
  category: job
  type: use-arg-job
  arg:
    - expected: someArg
      given: someArg
  sets: []
  deps: [sets-arg-2]
```

We may be able to keep this behavior as-is if we add the set-as spec field from  #116
